services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sagepick-core:local
    env_file:
      - .env.test
    environment:
      DATABASE_URL: postgresql://sagepick:sagepick@postgres:5432/sagepick
      REDIS_URL: redis://redis:6379/0
      MOVIE_DISCOVERY_START_DELAY_MINUTES: 0
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: sagepick
      POSTGRES_USER: sagepick
      POSTGRES_PASSWORD: sagepick
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sagepick -d sagepick"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data:
