services:
  sagepick-core:
    image: ghcr.io/saiteja-velpula/sagepick.core:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://sagepick:${POSTGRES_PASSWORD}@postgres:5432/sagepick
      REDIS_URL: redis://redis:6379/0
      MOVIE_DISCOVERY_START_DELAY_MINUTES: ${MOVIE_DISCOVERY_START_DELAY_MINUTES:-60}
      TMDB_MAX_REQUESTS_PER_SECOND: ${TMDB_MAX_REQUESTS_PER_SECOND:-15}
      TMDB_KEYWORD_CACHE_MAX_ENTRIES: ${TMDB_KEYWORD_CACHE_MAX_ENTRIES:-500000}
    ports:
      - "8101:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: sagepick
      POSTGRES_USER: sagepick
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sagepick -d sagepick"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis:7.4-alpine
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
