"""Add hydration tracking fields to Movie model

Revision ID: 22a8b5bd1b6d
Revises: f28e624e4e66
Create Date: 2025-11-13 12:55:20.360100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision: str = '22a8b5bd1b6d'
down_revision: Union[str, Sequence[str], None] = 'f28e624e4e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('is_hydrated', sa.Boolean(), nullable=False))
    op.add_column('movies', sa.Column('last_hydrated_at', sa.DateTime(), nullable=True))
    op.add_column('movies', sa.Column('hydration_source', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'hydration_source')
    op.drop_column('movies', 'last_hydrated_at')
    op.drop_column('movies', 'is_hydrated')
    # ### end Alembic commands ###
