"""Drop media category tables for Redis-based categories

Revision ID: 2a758d901326
Revises: 854792376e93
Create Date: 2025-10-29 16:25:07.390245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a758d901326'
down_revision: Union[str, Sequence[str], None] = '854792376e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the foreign key table first (it references media_categories)
    op.drop_table('media_category_movies')
    # Then drop the media_categories table and its index
    op.drop_index(op.f('ix_media_categories_name'), table_name='media_categories')
    op.drop_table('media_categories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_category_movies',
    sa.Column('media_category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['media_category_id'], ['media_categories.id'], name=op.f('media_category_movies_media_category_id_fkey')),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('media_category_movies_movie_id_fkey')),
    sa.PrimaryKeyConstraint('media_category_id', 'movie_id', name=op.f('media_category_movies_pkey'))
    )
    op.create_table('media_categories',
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('media_categories_pkey'))
    )
    op.create_index(op.f('ix_media_categories_name'), 'media_categories', ['name'], unique=True)
    # ### end Alembic commands ###
