"""Add MediaCategory and MediaCategoryMovie tables

Revision ID: 2d63525d440d
Revises: b05fc6fa11df
Create Date: 2025-10-15 07:00:07.932175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision: str = '2d63525d440d'
down_revision: Union[str, Sequence[str], None] = 'b05fc6fa11df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_categories',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_categories_name'), 'media_categories', ['name'], unique=True)
    op.create_table('media_category_movies',
    sa.Column('media_category_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_category_id'], ['media_categories.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('media_category_id', 'movie_id')
    )
    op.add_column('movies', sa.Column('budget', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('revenue', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'status')
    op.drop_column('movies', 'revenue')
    op.drop_column('movies', 'budget')
    op.drop_table('media_category_movies')
    op.drop_index(op.f('ix_media_categories_name'), table_name='media_categories')
    op.drop_table('media_categories')
    # ### end Alembic commands ###
