"""simplify job logs and status

Revision ID: 2f989961ca75
Revises: 96f122e56553
Create Date: 2025-10-23 02:58:55.784366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f989961ca75'
down_revision: Union[str, Sequence[str], None] = '96f122e56553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_logs', 'details')
    op.drop_column('job_logs', 'category_name')
    op.drop_column('job_logs', 'movie_id')
    op.drop_column('job_status', 'job_metadata')
    op.drop_column('job_status', 'error_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_status', sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('job_status', sa.Column('job_metadata', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('job_logs', sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('job_logs', sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('job_logs', sa.Column('details', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
