"""widen movie columns

Revision ID: 854792376e93
Revises: 2f989961ca75
Create Date: 2025-10-23 18:54:53.852214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '854792376e93'
down_revision: Union[str, Sequence[str], None] = '2f989961ca75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    op.alter_column('movies', 'original_title',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    op.alter_column('movies', 'budget',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               comment='Budget in USD',
               existing_nullable=True)
    op.alter_column('movies', 'revenue',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               comment='Revenue in USD',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'revenue',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               comment=None,
               existing_comment='Revenue in USD',
               existing_nullable=True)
    op.alter_column('movies', 'budget',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               comment=None,
               existing_comment='Budget in USD',
               existing_nullable=True)
    op.alter_column('movies', 'original_title',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('movies', 'title',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###
