"""add movie discovery state table

Revision ID: 96f122e56553
Revises: a6d92fbd1b8d
Create Date: 2025-10-23 02:22:44.613572

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f122e56553'
down_revision: Union[str, Sequence[str], None] = 'a6d92fbd1b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_discovery_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_page', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(
        sa.table(
            'movie_discovery_state',
            sa.column('id', sa.Integer()),
            sa.column('current_page', sa.Integer()),
            sa.column('updated_at', sa.DateTime()),
        ),
        [{'id': 1, 'current_page': 1, 'updated_at': datetime.utcnow()}],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_discovery_state')
    # ### end Alembic commands ###
