"""added desscription to categories

Revision ID: a6d92fbd1b8d
Revises: ed31b670a334
Create Date: 2025-10-21 14:31:26.891251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision: str = 'a6d92fbd1b8d'
down_revision: Union[str, Sequence[str], None] = 'ed31b670a334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_categories', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_categories', 'description')
    # ### end Alembic commands ###
