"""Initial v1 migrations


Revision ID: f28e624e4e66
Revises: 
Create Date: 2025-11-04 04:31:36.342262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision: str = 'f28e624e4e66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_tmdb_id'), 'genres', ['tmdb_id'], unique=True)
    op.create_table('job_status',
    sa.Column('job_type', sa.Enum('MOVIE_DISCOVERY', 'CHANGE_TRACKING', 'DATASET_EXPORT', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobexecutionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('processed_items', sa.Integer(), nullable=False),
    sa.Column('failed_items', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_tmdb_id'), 'keywords', ['tmdb_id'], unique=True)
    op.create_table('movie_discovery_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('current_page', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('original_title', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('overview', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('poster_path', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('backdrop_path', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('original_language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('popularity', sa.Float(), nullable=False),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('budget', sa.BigInteger(), nullable=True, comment='Budget in USD'),
    sa.Column('revenue', sa.BigInteger(), nullable=True, comment='Revenue in USD'),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('adult', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movies_tmdb_id'), 'movies', ['tmdb_id'], unique=True)
    op.create_table('job_logs',
    sa.Column('job_status_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('INFO', 'WARNING', 'ERROR', 'SUCCESS', name='loglevel'), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_status_id'], ['job_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie_genres',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id')
    )
    op.create_table('movie_keywords',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'keyword_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_keywords')
    op.drop_table('movie_genres')
    op.drop_table('job_logs')
    op.drop_index(op.f('ix_movies_tmdb_id'), table_name='movies')
    op.drop_table('movies')
    op.drop_table('movie_discovery_state')
    op.drop_index(op.f('ix_keywords_tmdb_id'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_table('job_status')
    op.drop_index(op.f('ix_genres_tmdb_id'), table_name='genres')
    op.drop_table('genres')
    # ### end Alembic commands ###
    
    # drop enums
    sa.Enum(name='loglevel').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='jobexecutionstatus').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='jobtype').drop(op.get_bind(), checkfirst=False)
